packages:
  - './packages/backend'
  - './packages/docsite'
  - './packages/frontend'

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  vue-demi: true

# pnpm 10
# onlyBuiltDependencies:
#   - '@nestjs/core'
#   - '@prisma/engines'
#   - '@scarf/scarf'
#   - esbuild
#   - prisma
#   - unrs-resolver
#   - vue-demi
