name: Pull Request Check - Production

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: pr-check-prod-${{ github.event.pull_request.id }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yaml
    secrets: inherit
